name: Build and Deploy
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: big213/nuxtjs-generate-action@v0.1.1
      - uses: jakejarvis/firebase-deploy-action@v0.1.0
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PUSHER_APP_KEY: 2de6fe0e624219475ded
          PUSHER_APP_CLUSTER: eu
          VER: ${{ github.ref }}
          API_URL: https://api-staging-cubezone.stackless.dev
          WCA_AUTH_URL: https://www.worldcubeassociation.org/oauth/authorize?client_id=TyQyedLpO0qMSmDcpC7G_7D09olryh4RLhmlNKiKJPI&response_type=code&scope=email+public&redirect_uri=https%3A%2F%2Fstaging.cube.zone%2Fwca-redirect
        with:
          args: "--only hosting:staging"