name: Build and Deploy
on:
  release:
    types: [created]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run generate
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:staging
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PUSHER_APP_KEY: 2de6fe0e624219475ded
          PUSHER_APP_CLUSTER: eu
          VER: ${{ github.ref }}
          API_URL: https://api-staging-cubezone.stackless.dev
          WCA_AUTH_URL: https://www.worldcubeassociation.org/oauth/authorize?client_id=TyQyedLpO0qMSmDcpC7G_7D09olryh4RLhmlNKiKJPI&response_type=code&scope=email+public&redirect_uri=https%3A%2F%2Fstaging.cube.zone%2Fwca-redirect
